# Generated by Django 4.2.7 on 2023-11-12 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardID', models.AutoField(primary_key=True, serialize=False)),
                ('boardType', models.SmallIntegerField()),
                ('title', models.TextField(max_length=30)),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('like_num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('state', models.BooleanField()),
                ('userID', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
